galaxy_info:
  role_name: alert_manager
  description: Запуск Alert Manager в Docker Swarm
  author: Dmitry Silinsky
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
