---
- name: Проверка, что Docker Swarm инициализирован
  community.docker.docker_swarm:
    state: present

- name: Установка меток ноды для Alert Manager
  community.docker.docker_node:
    hostname: "{{ ansible_hostname }}"
    labels:
      alertmanager: "true"
    labels_state: replace

- name: Создание файла настроек из шаблона
  ansible.builtin.template:
    src: templates/alertmanager.yml.j2
    dest: /tmp/alertmanager.yml
    mode: '644'

- name: Создание конфига с настройками Alert Manager
  block:
    - name: Чтение файла настроек Alert Manager с удалённого хоста
      ansible.builtin.slurp:
        src: /tmp/alertmanager.yml
      register: alertmanager_config_content

    - name: Создание конфига Docker для Alert Manager
      community.docker.docker_config:
        name: alertmanager_config
        data: "{{ alertmanager_config_content['content'] | b64decode }}"
        labels:
          config: "{{ alertmanager_config_content['content'] | hash('sha1') }}"
        state: present

    # - name: Удаление временного файла
    #   ansible.builtin.file:
    #     path: /tmp/alertmanager.yml
    #     state: absent

- name: Создание тома (volume) для данных alertmanager
  community.docker.docker_volume:
    name: alertmanager_data

- name: Запуск Alert Manager
  community.docker.docker_swarm_service:
    name: alertmanager
    image: prom/alertmanager
    state: present
    force_update: true
    replicas: 1
    networks:
      - name: "{{ network_name }}"
    publish:
      - mode: ingress
        protocol: tcp
        published_port: "{{ alertmanager.port }}"
        target_port: 9093
    labels:
      alertmanager: "true"
    configs:
      - config_name: alertmanager_config
        filename: /etc/alertmanager/alertmanager.yml
        mode: "444"
    mounts:
      - type: volume
        source: alertmanager_data
        target: /alertmanager
    args:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
