services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    deploy:
      mode: global
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - network1

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: /run/secrets/postgres.password
    secrets:
      - postgres.password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.database == true
    networks:
      - network1

configs:
  nginx_conf:
    file: ./nginx.conf

secrets:
  postgres.password:
    external: true

networks:
  network1:
    driver: overlay

volumes:
  postgres-data: