galaxy_info:
  role_name: prometheus
  description: Запуск Prometheus в Docker Swarm
  author: Dmitry Silinsky
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
